[2024-07-22T16:57:28.897+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T16:57:28.926+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-30T06:00:00+00:00 [queued]>
[2024-07-22T16:57:28.937+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-30T06:00:00+00:00 [queued]>
[2024-07-22T16:57:28.938+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T16:57:28.949+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extracta> on 2024-06-30 06:00:00+00:00
[2024-07-22T16:57:28.959+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=939) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T16:57:28.960+0000] {standard_task_runner.py:64} INFO - Started process 945 to run task
[2024-07-22T16:57:28.960+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extracta', 'scheduled__2024-06-30T06:00:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpj5_3ee_q']
[2024-07-22T16:57:28.962+0000] {standard_task_runner.py:91} INFO - Job 82: Subtask extracta
[2024-07-22T16:57:29.001+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extracta scheduled__2024-06-30T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T16:57:29.076+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extracta' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-30T06:00:00+00:00'
[2024-07-22T16:57:29.077+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T16:57:29.093+0000] {extract.py:127} INFO - Getting data of the table dtm_motower_gsm 
[2024-07-22T16:57:29.093+0000] {extract.py:128} INFO - where date is 2024-06-29
[2024-07-22T16:57:29.093+0000] {extract.py:103} INFO - get data to date 20240629
[2024-07-22T16:57:29.098+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T16:57:29.121+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T16:57:29.124+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286302f4410>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:29.526+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286302f5520>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:30.329+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286302f5940>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:31.931+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286302f5d60>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:35.134+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286302f5ee0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:35.136+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286302f65a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T16:57:35.137+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T16:57:35.137+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T16:57:35.149+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extracta, run_id=scheduled__2024-06-30T06:00:00+00:00, execution_date=20240630T060000, start_date=20240722T165728, end_date=20240722T165735
[2024-07-22T16:57:35.192+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T16:57:35.218+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T16:57:35.220+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:16:41.286+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:16:41.495+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-30T06:00:00+00:00 [queued]>
[2024-07-22T17:16:41.503+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-30T06:00:00+00:00 [queued]>
[2024-07-22T17:16:41.504+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:16:41.515+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extracta> on 2024-06-30 06:00:00+00:00
[2024-07-22T17:16:41.525+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1328) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:16:41.526+0000] {standard_task_runner.py:64} INFO - Started process 1334 to run task
[2024-07-22T17:16:41.527+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extracta', 'scheduled__2024-06-30T06:00:00+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpktamtmwl']
[2024-07-22T17:16:41.528+0000] {standard_task_runner.py:91} INFO - Job 129: Subtask extracta
[2024-07-22T17:16:41.566+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extracta scheduled__2024-06-30T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:16:41.642+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extracta' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-30T06:00:00+00:00'
[2024-07-22T17:16:41.643+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:16:41.657+0000] {extract.py:127} INFO - Getting data of the table dtm_motower_gsm 
[2024-07-22T17:16:41.657+0000] {extract.py:128} INFO - where date is 2024-06-29
[2024-07-22T17:16:41.657+0000] {extract.py:103} INFO - get data to date 20240629
[2024-07-22T17:16:41.662+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:16:41.684+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:16:41.687+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72864a7160c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:42.088+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72863031d010>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:42.890+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72863031d460>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:44.492+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72863031d7c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:47.695+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72863031dc70>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:47.697+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72863031e060>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T17:16:47.697+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:16:47.697+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:16:47.707+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extracta, run_id=scheduled__2024-06-30T06:00:00+00:00, execution_date=20240630T060000, start_date=20240722T171641, end_date=20240722T171647
[2024-07-22T17:16:47.753+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:16:47.761+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:43:31.381+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:43:31.676+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-30T06:00:00+00:00 [queued]>
[2024-07-22T17:43:31.688+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-30T06:00:00+00:00 [queued]>
[2024-07-22T17:43:31.688+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:43:31.699+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extracta> on 2024-06-30 06:00:00+00:00
[2024-07-22T17:43:31.711+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1825) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:43:31.712+0000] {standard_task_runner.py:64} INFO - Started process 1842 to run task
[2024-07-22T17:43:31.713+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extracta', 'scheduled__2024-06-30T06:00:00+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpcul4lzeu']
[2024-07-22T17:43:31.715+0000] {standard_task_runner.py:91} INFO - Job 179: Subtask extracta
[2024-07-22T17:43:31.762+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extracta scheduled__2024-06-30T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:43:31.865+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extracta' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-30T06:00:00+00:00'
[2024-07-22T17:43:31.867+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:43:31.884+0000] {extract.py:127} INFO - Getting data of the table dtm_motower_gsm 
[2024-07-22T17:43:31.885+0000] {extract.py:128} INFO - where date is 2024-06-29
[2024-07-22T17:43:31.886+0000] {extract.py:103} INFO - get data to date 20240629
[2024-07-22T17:43:31.892+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:43:31.928+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:43:31.971+0000] {rwminio.py:34} INFO - data in minio ok
[2024-07-22T17:43:31.972+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:43:31.973+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:43:31.983+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extracta, run_id=scheduled__2024-06-30T06:00:00+00:00, execution_date=20240630T060000, start_date=20240722T174331, end_date=20240722T174331
[2024-07-22T17:43:32.528+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:43:32.554+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T17:43:32.556+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
