[2024-07-22T16:57:20.081+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T16:57:20.113+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-06-29T06:00:00+00:00 [queued]>
[2024-07-22T16:57:20.124+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-06-29T06:00:00+00:00 [queued]>
[2024-07-22T16:57:20.124+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T16:57:20.135+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_congestion> on 2024-06-29 06:00:00+00:00
[2024-07-22T16:57:20.145+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=922) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T16:57:20.146+0000] {standard_task_runner.py:64} INFO - Started process 929 to run task
[2024-07-22T16:57:20.146+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_congestion', 'scheduled__2024-06-29T06:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpf63thcem']
[2024-07-22T16:57:20.148+0000] {standard_task_runner.py:91} INFO - Job 79: Subtask extract_congestion
[2024-07-22T16:57:20.188+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-06-29T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T16:57:20.261+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_congestion' AIRFLOW_CTX_EXECUTION_DATE='2024-06-29T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-29T06:00:00+00:00'
[2024-07-22T16:57:20.262+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T16:57:20.279+0000] {extract.py:127} INFO - Getting data of the table ks_hebdo_tdb_radio_drsi 
[2024-07-22T16:57:20.280+0000] {extract.py:128} INFO - where date is 2024-06-28
[2024-07-22T16:57:20.280+0000] {extract.py:99} INFO - get data to date 26 and year 2024
[2024-07-22T16:57:20.284+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T16:57:20.322+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T16:57:20.325+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bac1310>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:20.727+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bac1580>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:21.529+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bac1af0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:23.131+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bac1ee0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:26.333+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bac22d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:26.335+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bac2720>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T16:57:26.336+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T16:57:26.336+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T16:57:26.350+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_congestion, run_id=scheduled__2024-06-29T06:00:00+00:00, execution_date=20240629T060000, start_date=20240722T165720, end_date=20240722T165726
[2024-07-22T16:57:26.825+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T16:57:26.847+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T16:57:26.848+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:16:33.212+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:16:33.449+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-06-29T06:00:00+00:00 [queued]>
[2024-07-22T17:16:33.457+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-06-29T06:00:00+00:00 [queued]>
[2024-07-22T17:16:33.457+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:16:33.468+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_congestion> on 2024-06-29 06:00:00+00:00
[2024-07-22T17:16:33.478+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1319) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:16:33.479+0000] {standard_task_runner.py:64} INFO - Started process 1323 to run task
[2024-07-22T17:16:33.479+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_congestion', 'scheduled__2024-06-29T06:00:00+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmppjxkdra9']
[2024-07-22T17:16:33.481+0000] {standard_task_runner.py:91} INFO - Job 125: Subtask extract_congestion
[2024-07-22T17:16:33.525+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-06-29T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:16:33.613+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_congestion' AIRFLOW_CTX_EXECUTION_DATE='2024-06-29T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-29T06:00:00+00:00'
[2024-07-22T17:16:33.614+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:16:33.628+0000] {extract.py:127} INFO - Getting data of the table ks_hebdo_tdb_radio_drsi 
[2024-07-22T17:16:33.629+0000] {extract.py:128} INFO - where date is 2024-06-28
[2024-07-22T17:16:33.629+0000] {extract.py:99} INFO - get data to date 26 and year 2024
[2024-07-22T17:16:33.634+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:16:33.676+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:16:33.678+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286302a60c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:34.080+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bae4620>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:34.883+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bae4920>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:36.485+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bae4e30>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:39.687+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bae5280>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:39.689+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bae55e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T17:16:39.690+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:16:39.690+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:16:39.709+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_congestion, run_id=scheduled__2024-06-29T06:00:00+00:00, execution_date=20240629T060000, start_date=20240722T171633, end_date=20240722T171639
[2024-07-22T17:16:40.030+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:16:40.058+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T17:16:40.059+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:43:29.230+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:43:29.505+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-06-29T06:00:00+00:00 [queued]>
[2024-07-22T17:43:29.518+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-06-29T06:00:00+00:00 [queued]>
[2024-07-22T17:43:29.518+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:43:29.530+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_congestion> on 2024-06-29 06:00:00+00:00
[2024-07-22T17:43:29.542+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1802) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:43:29.544+0000] {standard_task_runner.py:64} INFO - Started process 1818 to run task
[2024-07-22T17:43:29.544+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_congestion', 'scheduled__2024-06-29T06:00:00+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpcn1e361y']
[2024-07-22T17:43:29.546+0000] {standard_task_runner.py:91} INFO - Job 173: Subtask extract_congestion
[2024-07-22T17:43:29.591+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-06-29T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:43:29.682+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_congestion' AIRFLOW_CTX_EXECUTION_DATE='2024-06-29T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-29T06:00:00+00:00'
[2024-07-22T17:43:29.683+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:43:29.700+0000] {extract.py:127} INFO - Getting data of the table ks_hebdo_tdb_radio_drsi 
[2024-07-22T17:43:29.701+0000] {extract.py:128} INFO - where date is 2024-06-28
[2024-07-22T17:43:29.701+0000] {extract.py:99} INFO - get data to date 26 and year 2024
[2024-07-22T17:43:29.707+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:43:29.770+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:43:29.858+0000] {rwminio.py:34} INFO - data in minio ok
[2024-07-22T17:43:29.864+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:43:29.864+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:43:29.875+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_congestion, run_id=scheduled__2024-06-29T06:00:00+00:00, execution_date=20240629T060000, start_date=20240722T174329, end_date=20240722T174329
[2024-07-22T17:43:29.925+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:43:29.966+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-22T17:43:29.968+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
