[2024-07-22T16:57:11.503+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T16:57:11.713+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-28T06:00:00+00:00 [queued]>
[2024-07-22T16:57:11.723+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-28T06:00:00+00:00 [queued]>
[2024-07-22T16:57:11.723+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T16:57:11.733+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extracta> on 2024-06-28 06:00:00+00:00
[2024-07-22T16:57:11.742+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=912) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T16:57:11.744+0000] {standard_task_runner.py:64} INFO - Started process 918 to run task
[2024-07-22T16:57:11.744+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extracta', 'scheduled__2024-06-28T06:00:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpl0sy2p8q']
[2024-07-22T16:57:11.746+0000] {standard_task_runner.py:91} INFO - Job 74: Subtask extracta
[2024-07-22T16:57:11.783+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extracta scheduled__2024-06-28T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T16:57:11.853+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extracta' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-28T06:00:00+00:00'
[2024-07-22T16:57:11.854+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T16:57:11.866+0000] {extract.py:127} INFO - Getting data of the table dtm_motower_gsm 
[2024-07-22T16:57:11.866+0000] {extract.py:128} INFO - where date is 2024-06-27
[2024-07-22T16:57:11.867+0000] {extract.py:103} INFO - get data to date 20240627
[2024-07-22T16:57:11.871+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T16:57:11.894+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T16:57:11.897+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304bb9b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:12.298+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304bbda0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:13.100+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304e0c80>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:14.702+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304e0500>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:17.904+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304e08c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:17.906+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304e0f20>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T16:57:17.906+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T16:57:17.907+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T16:57:17.915+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extracta, run_id=scheduled__2024-06-28T06:00:00+00:00, execution_date=20240628T060000, start_date=20240722T165711, end_date=20240722T165717
[2024-07-22T16:57:17.943+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T16:57:17.965+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T16:57:17.966+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:16:25.456+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:16:25.483+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-28T06:00:00+00:00 [queued]>
[2024-07-22T17:16:25.492+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-28T06:00:00+00:00 [queued]>
[2024-07-22T17:16:25.492+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:16:25.502+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extracta> on 2024-06-28 06:00:00+00:00
[2024-07-22T17:16:25.511+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1308) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:16:25.513+0000] {standard_task_runner.py:64} INFO - Started process 1315 to run task
[2024-07-22T17:16:25.513+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extracta', 'scheduled__2024-06-28T06:00:00+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpbo5988j8']
[2024-07-22T17:16:25.515+0000] {standard_task_runner.py:91} INFO - Job 124: Subtask extracta
[2024-07-22T17:16:25.553+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extracta scheduled__2024-06-28T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:16:25.639+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extracta' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-28T06:00:00+00:00'
[2024-07-22T17:16:25.640+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:16:25.654+0000] {extract.py:127} INFO - Getting data of the table dtm_motower_gsm 
[2024-07-22T17:16:25.654+0000] {extract.py:128} INFO - where date is 2024-06-27
[2024-07-22T17:16:25.654+0000] {extract.py:103} INFO - get data to date 20240627
[2024-07-22T17:16:25.658+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:16:25.680+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:16:25.682+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304d6d50>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:26.084+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286303551f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:26.886+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x728630355430>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:28.488+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x728630355760>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:31.691+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x728630355bb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:31.692+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x728630356060>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T17:16:31.693+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:16:31.693+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:16:31.703+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extracta, run_id=scheduled__2024-06-28T06:00:00+00:00, execution_date=20240628T060000, start_date=20240722T171625, end_date=20240722T171631
[2024-07-22T17:16:31.753+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:16:31.779+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T17:16:31.781+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:43:26.976+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:43:27.285+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-28T06:00:00+00:00 [queued]>
[2024-07-22T17:43:27.298+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-28T06:00:00+00:00 [queued]>
[2024-07-22T17:43:27.298+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:43:27.469+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extracta> on 2024-06-28 06:00:00+00:00
[2024-07-22T17:43:27.481+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1779) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:43:27.483+0000] {standard_task_runner.py:64} INFO - Started process 1792 to run task
[2024-07-22T17:43:27.483+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extracta', 'scheduled__2024-06-28T06:00:00+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpi8kvlrtv']
[2024-07-22T17:43:27.485+0000] {standard_task_runner.py:91} INFO - Job 164: Subtask extracta
[2024-07-22T17:43:27.538+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extracta scheduled__2024-06-28T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:43:27.645+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extracta' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-28T06:00:00+00:00'
[2024-07-22T17:43:27.647+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:43:27.668+0000] {extract.py:127} INFO - Getting data of the table dtm_motower_gsm 
[2024-07-22T17:43:27.668+0000] {extract.py:128} INFO - where date is 2024-06-27
[2024-07-22T17:43:27.668+0000] {extract.py:103} INFO - get data to date 20240627
[2024-07-22T17:43:27.674+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:43:27.706+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:43:27.748+0000] {rwminio.py:34} INFO - data in minio ok
[2024-07-22T17:43:27.749+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:43:27.750+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:43:27.759+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extracta, run_id=scheduled__2024-06-28T06:00:00+00:00, execution_date=20240628T060000, start_date=20240722T174327, end_date=20240722T174327
[2024-07-22T17:43:27.822+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:43:27.833+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
