[2024-07-22T16:57:03.545+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T16:57:03.763+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-27T06:00:00+00:00 [queued]>
[2024-07-22T16:57:03.772+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-27T06:00:00+00:00 [queued]>
[2024-07-22T16:57:03.773+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T16:57:03.782+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_trafic> on 2024-06-27 06:00:00+00:00
[2024-07-22T16:57:03.791+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=905) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T16:57:03.792+0000] {standard_task_runner.py:64} INFO - Started process 909 to run task
[2024-07-22T16:57:03.793+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_trafic', 'scheduled__2024-06-27T06:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmplbkdgj20']
[2024-07-22T16:57:03.794+0000] {standard_task_runner.py:91} INFO - Job 71: Subtask extract_trafic
[2024-07-22T16:57:03.834+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-27T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T16:57:03.909+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_trafic' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T06:00:00+00:00'
[2024-07-22T16:57:03.910+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T16:57:03.922+0000] {extract.py:127} INFO - Getting data of the table ks_daily_tdb_radio_drsi 
[2024-07-22T16:57:03.922+0000] {extract.py:128} INFO - where date is 2024-06-26
[2024-07-22T16:57:03.923+0000] {extract.py:103} INFO - get data to date 2024-06-26
[2024-07-22T16:57:03.927+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T16:57:03.966+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T16:57:03.970+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba92210>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:04.371+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba92510>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:05.173+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba929f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:06.775+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba92db0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:09.978+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba93050>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:09.980+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba93410>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T16:57:09.981+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T16:57:09.981+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T16:57:10.001+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_trafic, run_id=scheduled__2024-06-27T06:00:00+00:00, execution_date=20240627T060000, start_date=20240722T165703, end_date=20240722T165710
[2024-07-22T16:57:10.067+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T16:57:10.078+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:16:17.398+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:16:17.431+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-27T06:00:00+00:00 [queued]>
[2024-07-22T17:16:17.439+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-27T06:00:00+00:00 [queued]>
[2024-07-22T17:16:17.439+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:16:17.450+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_trafic> on 2024-06-27 06:00:00+00:00
[2024-07-22T17:16:17.460+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1293) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:16:17.462+0000] {standard_task_runner.py:64} INFO - Started process 1300 to run task
[2024-07-22T17:16:17.462+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_trafic', 'scheduled__2024-06-27T06:00:00+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpyjuapr20']
[2024-07-22T17:16:17.464+0000] {standard_task_runner.py:91} INFO - Job 121: Subtask extract_trafic
[2024-07-22T17:16:17.501+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-27T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:16:17.580+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_trafic' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T06:00:00+00:00'
[2024-07-22T17:16:17.581+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:16:17.594+0000] {extract.py:127} INFO - Getting data of the table ks_daily_tdb_radio_drsi 
[2024-07-22T17:16:17.594+0000] {extract.py:128} INFO - where date is 2024-06-26
[2024-07-22T17:16:17.594+0000] {extract.py:103} INFO - get data to date 2024-06-26
[2024-07-22T17:16:17.598+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:16:17.633+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:16:17.635+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862b910e00>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:18.036+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862b911340>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:18.838+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862b911730>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:20.441+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862b911a00>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:23.643+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862b911e20>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:23.645+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862b912300>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T17:16:23.646+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:16:23.646+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:16:23.660+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_trafic, run_id=scheduled__2024-06-27T06:00:00+00:00, execution_date=20240627T060000, start_date=20240722T171617, end_date=20240722T171623
[2024-07-22T17:16:23.691+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:16:23.701+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:43:24.527+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:43:24.873+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-27T06:00:00+00:00 [queued]>
[2024-07-22T17:43:24.902+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-27T06:00:00+00:00 [queued]>
[2024-07-22T17:43:24.903+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:43:24.931+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_trafic> on 2024-06-27 06:00:00+00:00
[2024-07-22T17:43:24.947+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1753) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:43:24.949+0000] {standard_task_runner.py:64} INFO - Started process 1768 to run task
[2024-07-22T17:43:24.951+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_trafic', 'scheduled__2024-06-27T06:00:00+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmp02dg8t9q']
[2024-07-22T17:43:24.954+0000] {standard_task_runner.py:91} INFO - Job 157: Subtask extract_trafic
[2024-07-22T17:43:25.030+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-27T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:43:25.149+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_trafic' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T06:00:00+00:00'
[2024-07-22T17:43:25.150+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:43:25.170+0000] {extract.py:127} INFO - Getting data of the table ks_daily_tdb_radio_drsi 
[2024-07-22T17:43:25.171+0000] {extract.py:128} INFO - where date is 2024-06-26
[2024-07-22T17:43:25.171+0000] {extract.py:103} INFO - get data to date 2024-06-26
[2024-07-22T17:43:25.178+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:43:25.253+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:43:25.350+0000] {rwminio.py:34} INFO - data in minio ok
[2024-07-22T17:43:25.357+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:43:25.358+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:43:25.369+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_trafic, run_id=scheduled__2024-06-27T06:00:00+00:00, execution_date=20240627T060000, start_date=20240722T174324, end_date=20240722T174325
[2024-07-22T17:43:25.408+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:43:25.419+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
