[2024-07-22T16:57:19.870+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T16:57:20.080+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-29T06:00:00+00:00 [queued]>
[2024-07-22T16:57:20.089+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-29T06:00:00+00:00 [queued]>
[2024-07-22T16:57:20.089+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T16:57:20.099+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extracta> on 2024-06-29 06:00:00+00:00
[2024-07-22T16:57:20.108+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=921) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T16:57:20.109+0000] {standard_task_runner.py:64} INFO - Started process 927 to run task
[2024-07-22T16:57:20.109+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extracta', 'scheduled__2024-06-29T06:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpwintpmkw']
[2024-07-22T16:57:20.111+0000] {standard_task_runner.py:91} INFO - Job 77: Subtask extracta
[2024-07-22T16:57:20.150+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extracta scheduled__2024-06-29T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T16:57:20.229+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extracta' AIRFLOW_CTX_EXECUTION_DATE='2024-06-29T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-29T06:00:00+00:00'
[2024-07-22T16:57:20.230+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T16:57:20.243+0000] {extract.py:127} INFO - Getting data of the table dtm_motower_gsm 
[2024-07-22T16:57:20.244+0000] {extract.py:128} INFO - where date is 2024-06-28
[2024-07-22T16:57:20.244+0000] {extract.py:103} INFO - get data to date 20240628
[2024-07-22T16:57:20.249+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T16:57:20.276+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T16:57:20.279+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304bbc80>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:20.681+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304bbfb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:21.482+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304e0050>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:23.084+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304e0740>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:26.287+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304e0ad0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:26.289+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304e1220>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T16:57:26.290+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T16:57:26.290+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T16:57:26.302+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extracta, run_id=scheduled__2024-06-29T06:00:00+00:00, execution_date=20240629T060000, start_date=20240722T165720, end_date=20240722T165726
[2024-07-22T16:57:26.789+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T16:57:26.810+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T16:57:26.811+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:16:33.435+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:16:33.464+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-29T06:00:00+00:00 [queued]>
[2024-07-22T17:16:33.472+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-29T06:00:00+00:00 [queued]>
[2024-07-22T17:16:33.472+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:16:33.483+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extracta> on 2024-06-29 06:00:00+00:00
[2024-07-22T17:16:33.492+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1318) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:16:33.493+0000] {standard_task_runner.py:64} INFO - Started process 1324 to run task
[2024-07-22T17:16:33.494+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extracta', 'scheduled__2024-06-29T06:00:00+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpxg6k8cn6']
[2024-07-22T17:16:33.496+0000] {standard_task_runner.py:91} INFO - Job 127: Subtask extracta
[2024-07-22T17:16:33.541+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extracta scheduled__2024-06-29T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:16:33.625+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extracta' AIRFLOW_CTX_EXECUTION_DATE='2024-06-29T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-29T06:00:00+00:00'
[2024-07-22T17:16:33.626+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:16:33.639+0000] {extract.py:127} INFO - Getting data of the table dtm_motower_gsm 
[2024-07-22T17:16:33.639+0000] {extract.py:128} INFO - where date is 2024-06-28
[2024-07-22T17:16:33.640+0000] {extract.py:103} INFO - get data to date 20240628
[2024-07-22T17:16:33.644+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:16:33.669+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:16:33.672+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x728630322e70>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:34.073+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x728630351730>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:34.876+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x728630351a90>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:36.478+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x728630351e80>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:39.681+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x728630352060>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:39.683+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x728630352600>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T17:16:39.684+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:16:39.684+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:16:39.696+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extracta, run_id=scheduled__2024-06-29T06:00:00+00:00, execution_date=20240629T060000, start_date=20240722T171633, end_date=20240722T171639
[2024-07-22T17:16:40.046+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:16:40.057+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:43:29.217+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:43:29.482+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-29T06:00:00+00:00 [queued]>
[2024-07-22T17:43:29.494+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-29T06:00:00+00:00 [queued]>
[2024-07-22T17:43:29.494+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:43:29.509+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extracta> on 2024-06-29 06:00:00+00:00
[2024-07-22T17:43:29.521+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1803) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:43:29.523+0000] {standard_task_runner.py:64} INFO - Started process 1817 to run task
[2024-07-22T17:43:29.523+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extracta', 'scheduled__2024-06-29T06:00:00+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmp10ha2ji_']
[2024-07-22T17:43:29.526+0000] {standard_task_runner.py:91} INFO - Job 172: Subtask extracta
[2024-07-22T17:43:29.571+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extracta scheduled__2024-06-29T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:43:29.657+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extracta' AIRFLOW_CTX_EXECUTION_DATE='2024-06-29T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-29T06:00:00+00:00'
[2024-07-22T17:43:29.658+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:43:29.674+0000] {extract.py:127} INFO - Getting data of the table dtm_motower_gsm 
[2024-07-22T17:43:29.674+0000] {extract.py:128} INFO - where date is 2024-06-28
[2024-07-22T17:43:29.674+0000] {extract.py:103} INFO - get data to date 20240628
[2024-07-22T17:43:29.680+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:43:29.707+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:43:29.742+0000] {rwminio.py:34} INFO - data in minio ok
[2024-07-22T17:43:29.743+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:43:29.743+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:43:29.754+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extracta, run_id=scheduled__2024-06-29T06:00:00+00:00, execution_date=20240629T060000, start_date=20240722T174329, end_date=20240722T174329
[2024-07-22T17:43:29.817+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:43:29.827+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
