[2024-07-22T16:57:03.588+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T16:57:03.810+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-27T06:00:00+00:00 [queued]>
[2024-07-22T16:57:03.818+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-27T06:00:00+00:00 [queued]>
[2024-07-22T16:57:03.819+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T16:57:03.829+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extracta> on 2024-06-27 06:00:00+00:00
[2024-07-22T16:57:03.838+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=903) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T16:57:03.839+0000] {standard_task_runner.py:64} INFO - Started process 910 to run task
[2024-07-22T16:57:03.839+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extracta', 'scheduled__2024-06-27T06:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpzk2r8y4v']
[2024-07-22T16:57:03.841+0000] {standard_task_runner.py:91} INFO - Job 72: Subtask extracta
[2024-07-22T16:57:03.879+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extracta scheduled__2024-06-27T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T16:57:03.952+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extracta' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T06:00:00+00:00'
[2024-07-22T16:57:03.953+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T16:57:03.966+0000] {extract.py:127} INFO - Getting data of the table dtm_motower_gsm 
[2024-07-22T16:57:03.966+0000] {extract.py:128} INFO - where date is 2024-06-26
[2024-07-22T16:57:03.967+0000] {extract.py:103} INFO - get data to date 20240626
[2024-07-22T16:57:03.972+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T16:57:03.992+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T16:57:03.994+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304bbcb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:04.396+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304e4050>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:05.197+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304e4200>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:06.799+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304e4950>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:10.001+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304e4bf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:10.004+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304e4ce0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T16:57:10.004+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T16:57:10.005+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T16:57:10.015+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extracta, run_id=scheduled__2024-06-27T06:00:00+00:00, execution_date=20240627T060000, start_date=20240722T165703, end_date=20240722T165710
[2024-07-22T16:57:10.073+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T16:57:10.100+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T16:57:10.102+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:16:17.166+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:16:17.381+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-27T06:00:00+00:00 [queued]>
[2024-07-22T17:16:17.390+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-27T06:00:00+00:00 [queued]>
[2024-07-22T17:16:17.391+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:16:17.403+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extracta> on 2024-06-27 06:00:00+00:00
[2024-07-22T17:16:17.414+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1292) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:16:17.416+0000] {standard_task_runner.py:64} INFO - Started process 1299 to run task
[2024-07-22T17:16:17.416+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extracta', 'scheduled__2024-06-27T06:00:00+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpfyogc4as']
[2024-07-22T17:16:17.417+0000] {standard_task_runner.py:91} INFO - Job 120: Subtask extracta
[2024-07-22T17:16:17.455+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extracta scheduled__2024-06-27T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:16:17.528+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extracta' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T06:00:00+00:00'
[2024-07-22T17:16:17.529+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:16:17.541+0000] {extract.py:127} INFO - Getting data of the table dtm_motower_gsm 
[2024-07-22T17:16:17.542+0000] {extract.py:128} INFO - where date is 2024-06-26
[2024-07-22T17:16:17.542+0000] {extract.py:103} INFO - get data to date 20240626
[2024-07-22T17:16:17.547+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:16:17.570+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:16:17.573+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286302ced50>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:17.974+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x728630334590>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:18.776+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286303349e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:20.379+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x728630334c80>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:23.581+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x728630335220>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:23.583+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286303358e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T17:16:23.583+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:16:23.584+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:16:23.593+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extracta, run_id=scheduled__2024-06-27T06:00:00+00:00, execution_date=20240627T060000, start_date=20240722T171617, end_date=20240722T171623
[2024-07-22T17:16:23.643+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:16:23.652+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:43:24.453+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:43:24.833+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-27T06:00:00+00:00 [queued]>
[2024-07-22T17:43:24.848+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extracta scheduled__2024-06-27T06:00:00+00:00 [queued]>
[2024-07-22T17:43:24.849+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:43:24.867+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extracta> on 2024-06-27 06:00:00+00:00
[2024-07-22T17:43:24.885+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1751) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:43:24.887+0000] {standard_task_runner.py:64} INFO - Started process 1764 to run task
[2024-07-22T17:43:24.887+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extracta', 'scheduled__2024-06-27T06:00:00+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmp4lxyta0d']
[2024-07-22T17:43:24.892+0000] {standard_task_runner.py:91} INFO - Job 153: Subtask extracta
[2024-07-22T17:43:24.961+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extracta scheduled__2024-06-27T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:43:25.100+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extracta' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T06:00:00+00:00'
[2024-07-22T17:43:25.101+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:43:25.124+0000] {extract.py:127} INFO - Getting data of the table dtm_motower_gsm 
[2024-07-22T17:43:25.124+0000] {extract.py:128} INFO - where date is 2024-06-26
[2024-07-22T17:43:25.124+0000] {extract.py:103} INFO - get data to date 20240626
[2024-07-22T17:43:25.133+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:43:25.173+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:43:25.219+0000] {rwminio.py:34} INFO - data in minio ok
[2024-07-22T17:43:25.220+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:43:25.221+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:43:25.235+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extracta, run_id=scheduled__2024-06-27T06:00:00+00:00, execution_date=20240627T060000, start_date=20240722T174324, end_date=20240722T174325
[2024-07-22T17:43:25.276+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:43:25.287+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
