[2024-07-22T16:56:46.100+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T16:56:46.371+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-25T06:00:00+00:00 [queued]>
[2024-07-22T16:56:46.382+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-25T06:00:00+00:00 [queued]>
[2024-07-22T16:56:46.383+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T16:56:46.396+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_trafic> on 2024-06-25 06:00:00+00:00
[2024-07-22T16:56:46.410+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=808) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T16:56:46.412+0000] {standard_task_runner.py:64} INFO - Started process 823 to run task
[2024-07-22T16:56:46.411+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_trafic', 'scheduled__2024-06-25T06:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpnxodk2yf']
[2024-07-22T16:56:46.414+0000] {standard_task_runner.py:91} INFO - Job 43: Subtask extract_trafic
[2024-07-22T16:56:46.453+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-25T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T16:56:46.546+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_trafic' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T06:00:00+00:00'
[2024-07-22T16:56:46.548+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T16:56:46.563+0000] {extract.py:127} INFO - Getting data of the table ks_daily_tdb_radio_drsi 
[2024-07-22T16:56:46.563+0000] {extract.py:128} INFO - where date is 2024-06-24
[2024-07-22T16:56:46.563+0000] {extract.py:103} INFO - get data to date 2024-06-24
[2024-07-22T16:56:46.568+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T16:56:46.615+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T16:56:46.619+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba91be0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:56:47.021+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba91eb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:56:47.822+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba92270>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:56:49.424+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba92570>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:56:52.626+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba92930>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:56:52.627+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba92a80>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T16:56:52.628+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T16:56:52.629+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T16:56:52.644+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_trafic, run_id=scheduled__2024-06-25T06:00:00+00:00, execution_date=20240625T060000, start_date=20240722T165646, end_date=20240722T165652
[2024-07-22T16:56:52.879+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T16:56:52.887+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:16:01.023+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:16:01.054+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-25T06:00:00+00:00 [queued]>
[2024-07-22T17:16:01.064+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-25T06:00:00+00:00 [queued]>
[2024-07-22T17:16:01.064+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:16:01.075+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_trafic> on 2024-06-25 06:00:00+00:00
[2024-07-22T17:16:01.086+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1204) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:16:01.087+0000] {standard_task_runner.py:64} INFO - Started process 1217 to run task
[2024-07-22T17:16:01.088+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_trafic', 'scheduled__2024-06-25T06:00:00+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpbnr0hb2z']
[2024-07-22T17:16:01.090+0000] {standard_task_runner.py:91} INFO - Job 94: Subtask extract_trafic
[2024-07-22T17:16:01.130+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-25T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:16:01.213+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_trafic' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T06:00:00+00:00'
[2024-07-22T17:16:01.215+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:16:01.231+0000] {extract.py:127} INFO - Getting data of the table ks_daily_tdb_radio_drsi 
[2024-07-22T17:16:01.232+0000] {extract.py:128} INFO - where date is 2024-06-24
[2024-07-22T17:16:01.232+0000] {extract.py:103} INFO - get data to date 2024-06-24
[2024-07-22T17:16:01.238+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:16:01.280+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:16:01.283+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x728630482360>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:01.684+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bafa960>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:02.486+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bafaf00>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:04.087+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bafb260>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:07.290+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bafb530>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:07.291+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bafb7a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T17:16:07.292+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:16:07.293+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:16:07.318+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_trafic, run_id=scheduled__2024-06-25T06:00:00+00:00, execution_date=20240625T060000, start_date=20240722T171601, end_date=20240722T171607
[2024-07-22T17:16:07.354+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:16:07.363+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:43:20.459+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:43:20.757+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-25T06:00:00+00:00 [queued]>
[2024-07-22T17:43:20.766+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-25T06:00:00+00:00 [queued]>
[2024-07-22T17:43:20.767+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:43:20.780+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_trafic> on 2024-06-25 06:00:00+00:00
[2024-07-22T17:43:20.795+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1700) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:43:20.797+0000] {standard_task_runner.py:64} INFO - Started process 1708 to run task
[2024-07-22T17:43:20.797+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_trafic', 'scheduled__2024-06-25T06:00:00+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpvcy1vyr0']
[2024-07-22T17:43:20.799+0000] {standard_task_runner.py:91} INFO - Job 137: Subtask extract_trafic
[2024-07-22T17:43:20.864+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-25T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:43:20.946+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_trafic' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T06:00:00+00:00'
[2024-07-22T17:43:20.947+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:43:20.961+0000] {extract.py:127} INFO - Getting data of the table ks_daily_tdb_radio_drsi 
[2024-07-22T17:43:20.961+0000] {extract.py:128} INFO - where date is 2024-06-24
[2024-07-22T17:43:20.962+0000] {extract.py:103} INFO - get data to date 2024-06-24
[2024-07-22T17:43:20.967+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:43:21.028+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:43:21.087+0000] {rwminio.py:34} INFO - data in minio ok
[2024-07-22T17:43:21.091+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:43:21.091+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:43:21.100+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_trafic, run_id=scheduled__2024-06-25T06:00:00+00:00, execution_date=20240625T060000, start_date=20240722T174320, end_date=20240722T174321
[2024-07-22T17:43:21.138+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:43:21.149+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
