[2024-07-22T16:57:28.699+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T16:57:28.923+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-06-30T06:00:00+00:00 [queued]>
[2024-07-22T16:57:28.932+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-06-30T06:00:00+00:00 [queued]>
[2024-07-22T16:57:28.932+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T16:57:28.943+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_congestion> on 2024-06-30 06:00:00+00:00
[2024-07-22T16:57:28.953+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=938) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T16:57:28.954+0000] {standard_task_runner.py:64} INFO - Started process 944 to run task
[2024-07-22T16:57:28.954+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_congestion', 'scheduled__2024-06-30T06:00:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpwnv58bv0']
[2024-07-22T16:57:28.956+0000] {standard_task_runner.py:91} INFO - Job 80: Subtask extract_congestion
[2024-07-22T16:57:28.996+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-06-30T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T16:57:29.073+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_congestion' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-30T06:00:00+00:00'
[2024-07-22T16:57:29.075+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T16:57:29.088+0000] {extract.py:127} INFO - Getting data of the table ks_hebdo_tdb_radio_drsi 
[2024-07-22T16:57:29.089+0000] {extract.py:128} INFO - where date is 2024-06-29
[2024-07-22T16:57:29.089+0000] {extract.py:99} INFO - get data to date 26 and year 2024
[2024-07-22T16:57:29.093+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T16:57:29.138+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T16:57:29.141+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72863047cbc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:29.542+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba475c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:30.344+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba47a10>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:31.947+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba47e30>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:35.149+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bb78260>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:35.151+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bb785c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T16:57:35.152+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T16:57:35.152+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T16:57:35.169+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_congestion, run_id=scheduled__2024-06-30T06:00:00+00:00, execution_date=20240630T060000, start_date=20240722T165728, end_date=20240722T165735
[2024-07-22T16:57:35.228+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T16:57:35.255+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T16:57:35.256+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:16:41.462+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:16:41.488+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-06-30T06:00:00+00:00 [queued]>
[2024-07-22T17:16:41.497+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-06-30T06:00:00+00:00 [queued]>
[2024-07-22T17:16:41.497+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:16:41.506+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_congestion> on 2024-06-30 06:00:00+00:00
[2024-07-22T17:16:41.515+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1326) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:16:41.516+0000] {standard_task_runner.py:64} INFO - Started process 1332 to run task
[2024-07-22T17:16:41.517+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_congestion', 'scheduled__2024-06-30T06:00:00+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpnsx5gr_a']
[2024-07-22T17:16:41.519+0000] {standard_task_runner.py:91} INFO - Job 130: Subtask extract_congestion
[2024-07-22T17:16:41.557+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-06-30T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:16:41.635+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_congestion' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-30T06:00:00+00:00'
[2024-07-22T17:16:41.636+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:16:41.651+0000] {extract.py:127} INFO - Getting data of the table ks_hebdo_tdb_radio_drsi 
[2024-07-22T17:16:41.651+0000] {extract.py:128} INFO - where date is 2024-06-29
[2024-07-22T17:16:41.651+0000] {extract.py:99} INFO - get data to date 26 and year 2024
[2024-07-22T17:16:41.656+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:16:41.697+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:16:41.699+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bac4b30>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:42.100+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bac4e90>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:42.902+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bac5280>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:44.505+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bac5640>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:47.707+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bac5b20>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:47.708+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bac5df0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T17:16:47.709+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:16:47.709+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:16:47.722+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_congestion, run_id=scheduled__2024-06-30T06:00:00+00:00, execution_date=20240630T060000, start_date=20240722T171641, end_date=20240722T171647
[2024-07-22T17:16:47.753+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:16:47.775+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T17:16:47.776+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:43:31.461+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:43:31.729+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-06-30T06:00:00+00:00 [queued]>
[2024-07-22T17:43:31.741+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-06-30T06:00:00+00:00 [queued]>
[2024-07-22T17:43:31.741+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:43:31.756+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_congestion> on 2024-06-30 06:00:00+00:00
[2024-07-22T17:43:31.770+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1826) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:43:31.771+0000] {standard_task_runner.py:64} INFO - Started process 1844 to run task
[2024-07-22T17:43:31.771+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_congestion', 'scheduled__2024-06-30T06:00:00+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpqf2hes8u']
[2024-07-22T17:43:31.774+0000] {standard_task_runner.py:91} INFO - Job 180: Subtask extract_congestion
[2024-07-22T17:43:31.825+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-06-30T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:43:31.932+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_congestion' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-30T06:00:00+00:00'
[2024-07-22T17:43:31.934+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:43:31.950+0000] {extract.py:127} INFO - Getting data of the table ks_hebdo_tdb_radio_drsi 
[2024-07-22T17:43:31.951+0000] {extract.py:128} INFO - where date is 2024-06-29
[2024-07-22T17:43:31.951+0000] {extract.py:99} INFO - get data to date 26 and year 2024
[2024-07-22T17:43:31.958+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:43:32.017+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:43:32.100+0000] {rwminio.py:34} INFO - data in minio ok
[2024-07-22T17:43:32.108+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:43:32.109+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:43:32.120+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_congestion, run_id=scheduled__2024-06-30T06:00:00+00:00, execution_date=20240630T060000, start_date=20240722T174331, end_date=20240722T174332
[2024-07-22T17:43:32.187+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:43:32.196+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
