[2024-07-22T16:56:55.894+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T16:56:55.930+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-26T06:00:00+00:00 [queued]>
[2024-07-22T16:56:55.945+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-26T06:00:00+00:00 [queued]>
[2024-07-22T16:56:55.945+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T16:56:55.965+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_trafic> on 2024-06-26 06:00:00+00:00
[2024-07-22T16:56:55.980+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=869) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T16:56:55.982+0000] {standard_task_runner.py:64} INFO - Started process 891 to run task
[2024-07-22T16:56:55.985+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_trafic', 'scheduled__2024-06-26T06:00:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpge5jsc6u']
[2024-07-22T16:56:55.989+0000] {standard_task_runner.py:91} INFO - Job 67: Subtask extract_trafic
[2024-07-22T16:56:56.048+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-26T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T16:56:56.153+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_trafic' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-26T06:00:00+00:00'
[2024-07-22T16:56:56.154+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T16:56:56.173+0000] {extract.py:127} INFO - Getting data of the table ks_daily_tdb_radio_drsi 
[2024-07-22T16:56:56.173+0000] {extract.py:128} INFO - where date is 2024-06-25
[2024-07-22T16:56:56.174+0000] {extract.py:103} INFO - get data to date 2024-06-25
[2024-07-22T16:56:56.179+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T16:56:56.251+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T16:56:56.254+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bafba10>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:56:56.656+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bafbe30>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:56:57.457+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba183b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:56:59.060+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba18740>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:02.262+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba18b30>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:02.264+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba18e60>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T16:57:02.265+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T16:57:02.265+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T16:57:02.288+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_trafic, run_id=scheduled__2024-06-26T06:00:00+00:00, execution_date=20240626T060000, start_date=20240722T165655, end_date=20240722T165702
[2024-07-22T16:57:02.333+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T16:57:02.344+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:16:09.102+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:16:09.400+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-26T06:00:00+00:00 [queued]>
[2024-07-22T17:16:09.416+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-26T06:00:00+00:00 [queued]>
[2024-07-22T17:16:09.416+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:16:09.434+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_trafic> on 2024-06-26 06:00:00+00:00
[2024-07-22T17:16:09.446+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1258) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:16:09.448+0000] {standard_task_runner.py:64} INFO - Started process 1279 to run task
[2024-07-22T17:16:09.449+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_trafic', 'scheduled__2024-06-26T06:00:00+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpfo1xym_g']
[2024-07-22T17:16:09.452+0000] {standard_task_runner.py:91} INFO - Job 111: Subtask extract_trafic
[2024-07-22T17:16:09.511+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-26T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:16:09.630+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_trafic' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-26T06:00:00+00:00'
[2024-07-22T17:16:09.631+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:16:09.648+0000] {extract.py:127} INFO - Getting data of the table ks_daily_tdb_radio_drsi 
[2024-07-22T17:16:09.649+0000] {extract.py:128} INFO - where date is 2024-06-25
[2024-07-22T17:16:09.649+0000] {extract.py:103} INFO - get data to date 2024-06-25
[2024-07-22T17:16:09.656+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:16:09.719+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:16:09.722+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba92180>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:10.124+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba923f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:10.926+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba92690>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:12.528+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba92900>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:15.730+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba92d20>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:15.732+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba92f30>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T17:16:15.733+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:16:15.733+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:16:15.755+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_trafic, run_id=scheduled__2024-06-26T06:00:00+00:00, execution_date=20240626T060000, start_date=20240722T171609, end_date=20240722T171615
[2024-07-22T17:16:15.802+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:16:15.814+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:43:22.706+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:43:22.743+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-26T06:00:00+00:00 [queued]>
[2024-07-22T17:43:22.757+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-26T06:00:00+00:00 [queued]>
[2024-07-22T17:43:22.758+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:43:22.774+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_trafic> on 2024-06-26 06:00:00+00:00
[2024-07-22T17:43:22.787+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1713) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:43:22.793+0000] {standard_task_runner.py:64} INFO - Started process 1736 to run task
[2024-07-22T17:43:22.790+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_trafic', 'scheduled__2024-06-26T06:00:00+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpha2fcnv6']
[2024-07-22T17:43:22.794+0000] {standard_task_runner.py:91} INFO - Job 148: Subtask extract_trafic
[2024-07-22T17:43:22.863+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-06-26T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:43:22.972+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_trafic' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-26T06:00:00+00:00'
[2024-07-22T17:43:22.977+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:43:22.997+0000] {extract.py:127} INFO - Getting data of the table ks_daily_tdb_radio_drsi 
[2024-07-22T17:43:22.998+0000] {extract.py:128} INFO - where date is 2024-06-25
[2024-07-22T17:43:22.998+0000] {extract.py:103} INFO - get data to date 2024-06-25
[2024-07-22T17:43:23.004+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:43:23.083+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:43:23.180+0000] {rwminio.py:34} INFO - data in minio ok
[2024-07-22T17:43:23.185+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:43:23.186+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:43:23.196+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_trafic, run_id=scheduled__2024-06-26T06:00:00+00:00, execution_date=20240626T060000, start_date=20240722T174322, end_date=20240722T174323
[2024-07-22T17:43:23.257+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:43:23.267+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
