[2024-07-25T10:18:58.525+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T10:18:58.570+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: enrich_prod.cleaning.cleaning_ihs scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-07-25T10:18:58.583+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: enrich_prod.cleaning.cleaning_ihs scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-07-25T10:18:58.584+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T10:18:58.609+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): cleaning.cleaning_ihs> on 2024-04-02 00:00:00+00:00
[2024-07-25T10:18:58.627+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=4525) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-25T10:18:58.629+0000] {standard_task_runner.py:64} INFO - Started process 4544 to run task
[2024-07-25T10:18:58.638+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'enrich_prod', 'cleaning.cleaning_ihs', 'scheduled__2024-04-02T00:00:00+00:00', '--job-id', '1089', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/enrich.py', '--cfg-path', '/tmp/tmp7tpkrevc']
[2024-07-25T10:18:58.648+0000] {standard_task_runner.py:91} INFO - Job 1089: Subtask cleaning.cleaning_ihs
[2024-07-25T10:18:58.786+0000] {task_command.py:426} INFO - Running <TaskInstance: enrich_prod.cleaning.cleaning_ihs scheduled__2024-04-02T00:00:00+00:00 [running]> on host b3845fb494d4
[2024-07-25T10:18:58.954+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='enrich_prod' AIRFLOW_CTX_TASK_ID='cleaning.cleaning_ihs' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-02T00:00:00+00:00'
[2024-07-25T10:18:58.955+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T10:18:58.974+0000] {logging_mixin.py:188} INFO - ['2024', '04', '02']
[2024-07-25T10:18:59.015+0000] {cleaning.py:181} INFO - read file OPEX_IHS/OPEX_IHS_202404.xlsx
[2024-07-25T10:18:59.963+0000] {cleaning.py:192} INFO - read OPEX_IHS/OPEX_IHS_202404.xlsx sheet OCI-MLL 1104 SIT Q2 -2024
[2024-07-25T10:18:59.968+0000] {cleaning.py:192} INFO - read OPEX_IHS/OPEX_IHS_202404.xlsx sheet OCI-MLL BPCI 22  SIT Q2- 2024
[2024-07-25T10:18:59.971+0000] {cleaning.py:192} INFO - read OPEX_IHS/OPEX_IHS_202404.xlsx sheet OCI-MLL BPCI 18  SIT Q2 - 2024
[2024-07-25T10:18:59.974+0000] {cleaning.py:192} INFO - read OPEX_IHS/OPEX_IHS_202404.xlsx sheet OCI-COLOC 398 SIT Q2 - 2024
[2024-07-25T10:18:59.976+0000] {cleaning.py:192} INFO - read OPEX_IHS/OPEX_IHS_202404.xlsx sheet OCI-PREST 193 ATHENA 1 Q2- 2024
[2024-07-25T10:18:59.978+0000] {cleaning.py:192} INFO - read OPEX_IHS/OPEX_IHS_202404.xlsx sheet OCI-ATHENA 2-125 SIT Q2- 2024
[2024-07-25T10:18:59.981+0000] {cleaning.py:192} INFO - read OPEX_IHS/OPEX_IHS_202404.xlsx sheet OCI-BTS 149 SIT Q2 - 2024
[2024-07-25T10:18:59.984+0000] {cleaning.py:192} INFO - read OPEX_IHS/OPEX_IHS_202404.xlsx sheet OCI-65 SIT  BARTER Q2 - 2024
[2024-07-25T10:18:59.987+0000] {cleaning.py:216} INFO - clean columns
[2024-07-25T10:18:59.994+0000] {cleaning.py:228} INFO - Add breakout data
[2024-07-25T10:18:59.997+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T10:18:59.998+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/gps/common/cleaning.py", line 235, in cleaning_ihs
    raise RuntimeError(f"No esco for {date}")
RuntimeError: No esco for 2024-04-02
[2024-07-25T10:19:00.014+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=enrich_prod, task_id=cleaning.cleaning_ihs, run_id=scheduled__2024-04-02T00:00:00+00:00, execution_date=20240402T000000, start_date=20240725T101858, end_date=20240725T101900
[2024-07-25T10:19:00.033+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-07-25T10:19:00.034+0000] {configuration.py:1053} WARNING - section/key [smtp/smtp_user] not found in config
[2024-07-25T10:19:00.034+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-07-25T10:19:00.048+0000] {configuration.py:1053} WARNING - section/key [smtp/smtp_user] not found in config
[2024-07-25T10:19:00.048+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-07-25T10:19:00.049+0000] {taskinstance.py:879} ERROR - Failed to send email to: ['richmond.kongo@orange.com', 'assane.diop@orange.com', 'cyrille1.danho@orange.com', 'mohamed2.sylla@orange.com', 'amadou.diomande@orange.com', 'Jonas.kouame@orange.com', 'armand.kablan@orange.com', 'anicet.azombade@orange.com', 'etienne.kouadio@orange.com', 'bertine.kouakou@orange.com', 'florentine.kouakou@orange.com', 'ange.phaceli@orange.com', 'soulegame.soro@orange.com', 'innocent.yengo@orange.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2676, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2701, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/gps/common/cleaning.py", line 235, in cleaning_ihs
    raise RuntimeError(f"No esco for {date}")
RuntimeError: No esco for 2024-04-02

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1063, in _email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 853, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 838, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 877, in _handle_failure
    task_instance.email_alert(error, failure_context["task"])
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3163, in email_alert
    _email_alert(task_instance=self, exception=exception, task=task)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1065, in _email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 853, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 838, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-07-25T10:19:00.056+0000] {alerting.py:71} INFO - send alert mail to richmond.kongo@orange.com, assane.diop@orange.com, cyrille1.danho@orange.com, mohamed2.sylla@orange.com, amadou.diomande@orange.com, Jonas.kouame@orange.com, armand.kablan@orange.com, anicet.azombade@orange.com, etienne.kouadio@orange.com, bertine.kouakou@orange.com, florentine.kouakou@orange.com, ange.phaceli@orange.com, soulegame.soro@orange.com, innocent.yengo@orange.com
[2024-07-25T10:19:00.056+0000] {alerting.py:30} INFO - Sending mail ... 
[2024-07-25T10:19:00.057+0000] {alerting.py:38} ERROR - Failed to send email: please run connect() first
[2024-07-25T10:19:00.101+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1089 for task cleaning.cleaning_ihs (No esco for 2024-04-02; 4544)
[2024-07-25T10:19:00.166+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T10:19:00.179+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-25T10:23:26.837+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T10:23:27.421+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: enrich_prod.cleaning.cleaning_ihs scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-07-25T10:23:27.438+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: enrich_prod.cleaning.cleaning_ihs scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-07-25T10:23:27.439+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T10:23:27.487+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): cleaning.cleaning_ihs> on 2024-04-02 00:00:00+00:00
[2024-07-25T10:23:27.511+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=4685) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-25T10:23:27.513+0000] {standard_task_runner.py:64} INFO - Started process 4713 to run task
[2024-07-25T10:23:27.516+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'enrich_prod', 'cleaning.cleaning_ihs', 'scheduled__2024-04-02T00:00:00+00:00', '--job-id', '1122', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/enrich.py', '--cfg-path', '/tmp/tmpfd_35uuf']
[2024-07-25T10:23:27.518+0000] {standard_task_runner.py:91} INFO - Job 1122: Subtask cleaning.cleaning_ihs
[2024-07-25T10:23:27.640+0000] {task_command.py:426} INFO - Running <TaskInstance: enrich_prod.cleaning.cleaning_ihs scheduled__2024-04-02T00:00:00+00:00 [running]> on host b3845fb494d4
[2024-07-25T10:23:27.841+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='enrich_prod' AIRFLOW_CTX_TASK_ID='cleaning.cleaning_ihs' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-02T00:00:00+00:00'
[2024-07-25T10:23:27.842+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T10:23:27.862+0000] {logging_mixin.py:188} INFO - ['2024', '04', '02']
[2024-07-25T10:23:27.887+0000] {cleaning.py:181} INFO - read file OPEX_IHS/OPEX_IHS_202404.xlsx
[2024-07-25T10:23:29.532+0000] {cleaning.py:192} INFO - read OPEX_IHS/OPEX_IHS_202404.xlsx sheet OCI-MLL 1104 SIT Q2 -2024
[2024-07-25T10:23:29.538+0000] {cleaning.py:192} INFO - read OPEX_IHS/OPEX_IHS_202404.xlsx sheet OCI-MLL BPCI 22  SIT Q2- 2024
[2024-07-25T10:23:29.542+0000] {cleaning.py:192} INFO - read OPEX_IHS/OPEX_IHS_202404.xlsx sheet OCI-MLL BPCI 18  SIT Q2 - 2024
[2024-07-25T10:23:29.545+0000] {cleaning.py:192} INFO - read OPEX_IHS/OPEX_IHS_202404.xlsx sheet OCI-COLOC 398 SIT Q2 - 2024
[2024-07-25T10:23:29.548+0000] {cleaning.py:192} INFO - read OPEX_IHS/OPEX_IHS_202404.xlsx sheet OCI-PREST 193 ATHENA 1 Q2- 2024
[2024-07-25T10:23:29.552+0000] {cleaning.py:192} INFO - read OPEX_IHS/OPEX_IHS_202404.xlsx sheet OCI-ATHENA 2-125 SIT Q2- 2024
[2024-07-25T10:23:29.555+0000] {cleaning.py:192} INFO - read OPEX_IHS/OPEX_IHS_202404.xlsx sheet OCI-BTS 149 SIT Q2 - 2024
[2024-07-25T10:23:29.558+0000] {cleaning.py:192} INFO - read OPEX_IHS/OPEX_IHS_202404.xlsx sheet OCI-65 SIT  BARTER Q2 - 2024
[2024-07-25T10:23:29.561+0000] {cleaning.py:216} INFO - clean columns
[2024-07-25T10:23:29.577+0000] {cleaning.py:228} INFO - Add breakout data
[2024-07-25T10:23:29.642+0000] {cleaning.py:253} INFO - save to minio
[2024-07-25T10:23:29.643+0000] {rwminio.py:19} INFO - start to save data
[2024-07-25T10:23:29.770+0000] {rwminio.py:34} INFO - data in minio ok
[2024-07-25T10:23:29.771+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T10:23:29.771+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T10:23:29.791+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=enrich_prod, task_id=cleaning.cleaning_ihs, run_id=scheduled__2024-04-02T00:00:00+00:00, execution_date=20240402T000000, start_date=20240725T102327, end_date=20240725T102329
[2024-07-25T10:23:29.927+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T10:23:29.955+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
