[2024-07-22T16:57:36.548+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T16:57:36.581+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-07-01T06:00:00+00:00 [queued]>
[2024-07-22T16:57:36.595+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-07-01T06:00:00+00:00 [queued]>
[2024-07-22T16:57:36.595+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T16:57:36.606+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_trafic> on 2024-07-01 06:00:00+00:00
[2024-07-22T16:57:36.616+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=946) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T16:57:36.618+0000] {standard_task_runner.py:64} INFO - Started process 954 to run task
[2024-07-22T16:57:36.618+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_trafic', 'scheduled__2024-07-01T06:00:00+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpc1zs2cyn']
[2024-07-22T16:57:36.620+0000] {standard_task_runner.py:91} INFO - Job 85: Subtask extract_trafic
[2024-07-22T16:57:36.660+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-07-01T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T16:57:36.734+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_trafic' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T06:00:00+00:00'
[2024-07-22T16:57:36.735+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T16:57:36.750+0000] {extract.py:127} INFO - Getting data of the table ks_daily_tdb_radio_drsi 
[2024-07-22T16:57:36.750+0000] {extract.py:128} INFO - where date is 2024-06-30
[2024-07-22T16:57:36.750+0000] {extract.py:103} INFO - get data to date 2024-06-30
[2024-07-22T16:57:36.755+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T16:57:36.786+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T16:57:36.789+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bb95d90>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:37.190+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bb96390>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:37.992+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bb96750>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:39.595+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bb96bd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:42.798+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bb97050>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:42.800+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bb973e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T16:57:42.801+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T16:57:42.801+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T16:57:42.813+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_trafic, run_id=scheduled__2024-07-01T06:00:00+00:00, execution_date=20240701T060000, start_date=20240722T165736, end_date=20240722T165742
[2024-07-22T16:57:42.975+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T16:57:42.986+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:16:49.862+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:16:49.891+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-07-01T06:00:00+00:00 [queued]>
[2024-07-22T17:16:49.899+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-07-01T06:00:00+00:00 [queued]>
[2024-07-22T17:16:49.899+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:16:49.910+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_trafic> on 2024-07-01 06:00:00+00:00
[2024-07-22T17:16:49.919+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1335) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:16:49.920+0000] {standard_task_runner.py:64} INFO - Started process 1342 to run task
[2024-07-22T17:16:49.921+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_trafic', 'scheduled__2024-07-01T06:00:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmp2ix3myvu']
[2024-07-22T17:16:49.923+0000] {standard_task_runner.py:91} INFO - Job 133: Subtask extract_trafic
[2024-07-22T17:16:49.962+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-07-01T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:16:50.033+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_trafic' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T06:00:00+00:00'
[2024-07-22T17:16:50.034+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:16:50.046+0000] {extract.py:127} INFO - Getting data of the table ks_daily_tdb_radio_drsi 
[2024-07-22T17:16:50.046+0000] {extract.py:128} INFO - where date is 2024-06-30
[2024-07-22T17:16:50.046+0000] {extract.py:103} INFO - get data to date 2024-06-30
[2024-07-22T17:16:50.050+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:16:50.085+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:16:50.088+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x728630322a80>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:50.489+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bb99490>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:51.292+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bb998b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:52.894+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bb99ca0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:56.096+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bb99fa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:56.098+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bb9a330>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T17:16:56.098+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:16:56.099+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:16:56.109+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_trafic, run_id=scheduled__2024-07-01T06:00:00+00:00, execution_date=20240701T060000, start_date=20240722T171649, end_date=20240722T171656
[2024-07-22T17:16:56.149+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:16:56.158+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:43:34.324+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:43:34.530+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-07-01T06:00:00+00:00 [queued]>
[2024-07-22T17:43:34.537+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-07-01T06:00:00+00:00 [queued]>
[2024-07-22T17:43:34.537+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:43:34.546+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_trafic> on 2024-07-01 06:00:00+00:00
[2024-07-22T17:43:34.556+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1860) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:43:34.557+0000] {standard_task_runner.py:64} INFO - Started process 1865 to run task
[2024-07-22T17:43:34.557+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_trafic', 'scheduled__2024-07-01T06:00:00+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmp0e6lxf42']
[2024-07-22T17:43:34.559+0000] {standard_task_runner.py:91} INFO - Job 190: Subtask extract_trafic
[2024-07-22T17:43:34.595+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_trafic scheduled__2024-07-01T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:43:34.663+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_trafic' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T06:00:00+00:00'
[2024-07-22T17:43:34.664+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:43:34.677+0000] {extract.py:127} INFO - Getting data of the table ks_daily_tdb_radio_drsi 
[2024-07-22T17:43:34.677+0000] {extract.py:128} INFO - where date is 2024-06-30
[2024-07-22T17:43:34.677+0000] {extract.py:103} INFO - get data to date 2024-06-30
[2024-07-22T17:43:34.681+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:104: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:43:34.713+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:43:34.764+0000] {rwminio.py:34} INFO - data in minio ok
[2024-07-22T17:43:34.766+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:43:34.767+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:43:34.777+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_trafic, run_id=scheduled__2024-07-01T06:00:00+00:00, execution_date=20240701T060000, start_date=20240722T174334, end_date=20240722T174334
[2024-07-22T17:43:34.810+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:43:34.821+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
