[2024-07-22T16:57:36.341+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T16:57:36.555+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-07-01T06:00:00+00:00 [queued]>
[2024-07-22T16:57:36.563+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-07-01T06:00:00+00:00 [queued]>
[2024-07-22T16:57:36.563+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T16:57:36.573+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_congestion> on 2024-07-01 06:00:00+00:00
[2024-07-22T16:57:36.585+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=947) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T16:57:36.587+0000] {standard_task_runner.py:64} INFO - Started process 952 to run task
[2024-07-22T16:57:36.587+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_congestion', 'scheduled__2024-07-01T06:00:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmp373h8x3p']
[2024-07-22T16:57:36.589+0000] {standard_task_runner.py:91} INFO - Job 84: Subtask extract_congestion
[2024-07-22T16:57:36.629+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-07-01T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T16:57:36.708+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_congestion' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T06:00:00+00:00'
[2024-07-22T16:57:36.709+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T16:57:36.720+0000] {extract.py:127} INFO - Getting data of the table ks_hebdo_tdb_radio_drsi 
[2024-07-22T16:57:36.720+0000] {extract.py:128} INFO - where date is 2024-06-30
[2024-07-22T16:57:36.721+0000] {extract.py:99} INFO - get data to date 26 and year 2024
[2024-07-22T16:57:36.725+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T16:57:36.768+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T16:57:36.771+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba474d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:37.172+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba476b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:37.975+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba47a70>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:39.578+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba47e30>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:42.780+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bb780b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T16:57:42.782+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862bb78530>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T16:57:42.783+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T16:57:42.783+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T16:57:42.798+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_congestion, run_id=scheduled__2024-07-01T06:00:00+00:00, execution_date=20240701T060000, start_date=20240722T165736, end_date=20240722T165742
[2024-07-22T16:57:42.991+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T16:57:43.017+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T16:57:43.018+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:16:49.672+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:16:49.887+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-07-01T06:00:00+00:00 [queued]>
[2024-07-22T17:16:49.896+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-07-01T06:00:00+00:00 [queued]>
[2024-07-22T17:16:49.896+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:16:49.905+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_congestion> on 2024-07-01 06:00:00+00:00
[2024-07-22T17:16:49.914+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1336) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:16:49.916+0000] {standard_task_runner.py:64} INFO - Started process 1341 to run task
[2024-07-22T17:16:49.916+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_congestion', 'scheduled__2024-07-01T06:00:00+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpnq84g7tg']
[2024-07-22T17:16:49.918+0000] {standard_task_runner.py:91} INFO - Job 131: Subtask extract_congestion
[2024-07-22T17:16:49.957+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-07-01T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:16:50.031+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_congestion' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T06:00:00+00:00'
[2024-07-22T17:16:50.032+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:16:50.045+0000] {extract.py:127} INFO - Getting data of the table ks_hebdo_tdb_radio_drsi 
[2024-07-22T17:16:50.046+0000] {extract.py:128} INFO - where date is 2024-06-30
[2024-07-22T17:16:50.046+0000] {extract.py:99} INFO - get data to date 26 and year 2024
[2024-07-22T17:16:50.050+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:16:50.092+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:16:50.094+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7286304edd90>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:50.495+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba94920>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:51.297+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba94c80>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:52.899+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba94fe0>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:56.100+0000] {connectionpool.py:872} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba95310>: Failed to establish a new connection: [Errno 111] Connection refused')': /motower?location=
[2024-07-22T17:16:56.101+0000] {rwminio.py:36} ERROR - Error saving data to Minio with error: HTTPConnectionPool(host='minio', port=80): Max retries exceeded with url: /motower?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72862ba95610>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-07-22T17:16:56.102+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:16:56.102+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:16:56.113+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_congestion, run_id=scheduled__2024-07-01T06:00:00+00:00, execution_date=20240701T060000, start_date=20240722T171649, end_date=20240722T171656
[2024-07-22T17:16:56.149+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:16:56.157+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:43:33.753+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:43:33.996+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-07-01T06:00:00+00:00 [queued]>
[2024-07-22T17:43:34.006+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-07-01T06:00:00+00:00 [queued]>
[2024-07-22T17:43:34.006+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:43:34.018+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_congestion> on 2024-07-01 06:00:00+00:00
[2024-07-22T17:43:34.030+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1854) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:43:34.032+0000] {standard_task_runner.py:64} INFO - Started process 1863 to run task
[2024-07-22T17:43:34.032+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'extract_congestion', 'scheduled__2024-07-01T06:00:00+00:00', '--job-id', '188', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpu9o_ia79']
[2024-07-22T17:43:34.034+0000] {standard_task_runner.py:91} INFO - Job 188: Subtask extract_congestion
[2024-07-22T17:43:34.078+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.extract_congestion scheduled__2024-07-01T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:43:34.151+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='extract_congestion' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T06:00:00+00:00'
[2024-07-22T17:43:34.152+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:43:34.165+0000] {extract.py:127} INFO - Getting data of the table ks_hebdo_tdb_radio_drsi 
[2024-07-22T17:43:34.166+0000] {extract.py:128} INFO - where date is 2024-06-30
[2024-07-22T17:43:34.166+0000] {extract.py:99} INFO - get data to date 26 and year 2024
[2024-07-22T17:43:34.171+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:43:34.220+0000] {rwminio.py:19} INFO - start to save data
[2024-07-22T17:43:34.275+0000] {rwminio.py:34} INFO - data in minio ok
[2024-07-22T17:43:34.280+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-22T17:43:34.281+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:43:34.289+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=motower_daily_prod, task_id=extract_congestion, run_id=scheduled__2024-07-01T06:00:00+00:00, execution_date=20240701T060000, start_date=20240722T174333, end_date=20240722T174334
[2024-07-22T17:43:34.325+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-22T17:43:34.346+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-22T17:43:34.348+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
